version: '3'
services:
  db:
    image: "postgres:9.4"
    env_file: db.env

  manager:
    build: .
    image: "manager:latest"
    depends_on:
      - db
    env_file: db.env
    environment:
      - CSV_FILENAME=data.csv