version: '3'
services:
  db:
    image: "postgres:9.4"
    hostname: db
    env_file: db.env
    ports:
      - "5432:5432"

  manager:
    build: .
    image: "manager:latest"
    container_name: manager
    depends_on:
      - db
    env_file: db.env
    environment:
      - CSV_FILENAME=data.csv